docxtpl/__init__.py

The tempfile `/tmp/titi` does not appear to be used elsewhere in the code. It creates however a compatibility problem in Windows. I suggest it should be removed.

Remove temp file in render_xml

---

docxtpl/__init__.py

The character \n is not escaped correctly, which causes that the line break does not appear in any office version.
(Open office, Libre office or Microsoft office).
In my case, this fixed that problem.

Fix bug with enter in RichText.

---

docxtpl/__init__.py

Added a new method for picture replacement in the file.
The user must include the picture picture as in the past and take note of the original picture name. Then, he can call the new method replace_pic to have it replaced with a new file. There is no need to keep the original file anymore and the (fragile) crc comparison was eliminated. Moreover the new approach does NOT require post-processing.

New method for image replacement

---

docxtpl/__init__.py

for https://github.com/elapouya/python-docx-template/issues/101
I add an parameter for new_subdoc() function. 
Now one can use new_subdoc(docfilename) to insert an exist document as subdocument

Insert exist document as subdocument

---

tests/template_error.py

I've replaced `print` instruction with call of a `six` package's implementation compatible with Python 2 as well as Python 3.

Fix test incompatibility with Python 3 versions

---

docxtpl/__init__.py

tested on word for macOS, version 16.17 (180909). Documentation found here: http://www.datypic.com/sc/ooxml/e-w_vertAlign-1.html

added props for sub and super

---

docxtpl/__init__.py

xml tag has't close valid tag <w:pPr>

Fix invalid xml parse because using {%vm%}

---

docxtpl/__init__.py

In some cases where you have to deal with a large number of documents, it'd be ideal if you can see the variables that are needed directly from the CLI instead of opening up all those documents and figure out yourself.

Getting undeclared variables in a template

---

setup.py

When creating a conda package from the package on pypi, setup.py crashes in `get_version(pkg)` due to choking on an `\x9d` while reading `__init__.py`. Apparently because on Windows, the default encoding `open()` isn't UTF-8... instead it tries using [CP-1252](https://en.wikipedia.org/wiki/Windows-1252) and `\x9d` has no meaning in CP-1252. 
Explicitly specifying UTF-8 encoding in `open()` fixes this.
Similar to
https://stackoverflow.com/a/9233174/119775
and
https://stackoverflow.com/a/31838862/119775

Explicitly specify utf-8 encoding when opening file in setup.py

---

docxtpl/__init__.py
tests/header_footer_image_file_obj.py

Sorry, this was actually supposed to be part of the original PR for file-like object support. I thought Github automatically updated PRs based on forks.
The test better outline saving to file-like objects without any modifications outside of docxtpl

Fix need to "Recover document" after using replace_media and saving to file-like object

---

docxtpl/__init__.py

Fixing this issue: https://github.com/elapouya/python-docx-template/issues/204

Handle spaces correctly when run are split by Jinja code

---

docxtpl/__init__.py

Fixes #208 
Changes `undeclared_template_variables` to be a method instead of property.

Allow jinja environment to be passed to undeclared_template_variables

---

docxtpl/__init__.py

Adding a truncation to the file object that is passed. This makes sure that the zip file's table of contents is re-written after the new pictures have been added. If the picture size changed too much the table of contents would be incorrect causing Microsoft word to have to open the document in recovery mode and fix the zip file. This fixes that issue.

Truncate zip file before re-writing it for  replace_media with file-like objects

---

docxtpl/__init__.py
tests/richtext.py

Hi,
First, thank you for sharing your library.
This PR allows to add a RichText object to another one. I use this in case in which some sentences parts are computed by a function. Example : 
<pre>def generate_rt_people(people):
rt = RichText()
rt.add("{} ".format(people.firstname))
rt.add(people.lastname, bold=True, underline=True)
return rt
two_peoples = RichText()
two_peoples .add(people1)
two_peoples .add(' and ')
two_peoples .add(people2)</pre>

Add the ability to add a RichText object to another RichText object

---

docxtpl/__init__.py

Using Python 3.8.2, lxml 4.5.0 , tests failed with the following traceback:
```
Traceback (most recent call last):
File "./custom_jinja_filters.py", line 32, in <module>
tpl.render(context, jinja_env)
File "/Users/x/src/python-docx-template/docxtpl/__init__.py", line 276, in render
for relKey, xml in headers:
File "/Users/x/src/python-docx-template/docxtpl/__init__.py", line 249, in build_headers_footers_xml
for relKey, xml in self.get_headers_footers_xml(uri):
File "/Users/x/src/python-docx-template/docxtpl/__init__.py", line 240, in get_headers_footers_xml
yield relKey, self.xml_to_string(parse_xml(val._target._blob))
File "/Users/x/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/docx/opc/oxml.py", line 37, in parse_xml
return etree.fromstring(text, …
```

Prevent lxml from attempting to parse None

---

docs/index.rst

This will enabling RichText section in the documentation as it appears
after the concerened section. Easier to navigate and avoid confusion.

Reference RichText section

---

docxtpl/__init__.py
setup.py

This fixes headers and footers for me in both 0.8.7 and 0.8.10. Fixes #246 
It does the following:
- Use proper properties (`target_part` and `blob`) in `get_headers_footers_xml`
- Replace the `Relationship` target using `XmlPart.load`
Problems:
- Image replacement in headers (all tests regarding this) does not work for me in 0.8.7 and the behaviour is the same in 0.8.10. I assume this was already broken.
Please let me know if this change looks good to you.

Make headers and footers work with both python-docx 0.8.7 and 0.8.10

---

docxtpl/__init__.py
setup.py

Attempt 2 - see #263 . Fixes #246 .
There was indeed something wrong with my old attempt. I've copied the rels into the newly created part in this attempt.
Note that these changes use only public API (no `_` or `__` functions/properties) so hopefully they are more forwards compatible than the old code.
PS. Please don't merge this unless you are convinced this one is correct, that is easier for both of us.

Make headers and footers work with both python-docx 0.8.7 and 0.8.10 #2

---

docs/index.rst
docxtpl/__init__.py

There is a small typo in docs/index.rst, docxtpl/__init__.py.
Should read `embedded` rather than `embdded`.

docs: Fix simple typo, embdded -> embedded

---

docxtpl/__init__.py

Now line breaks are added for the '\ a' tags while maintaining paragraph and run styles. Also it preserves the given numbering (or bullet points #73 )
No need to use Listing()

Add line break resolving with styles preserving

---

docxtpl/__init__.py

Reverts elapouya/python-docx-template#307
After testing, it appears the style is not preserved.
I just added in tests/escape.py in context : 
```
'new_listing': """With the latest version of docxtpl,
there is no need to use Listing objects anymore.
Just use \\n for newline,\n\\t for \ttabulation and \\f for ...\f...page break"""
```
and add `{{ new_listing }}` in tests/templates/escape_tpl.docx
The styling is lost after the tabulation

Revert "Add line break resolving with styles preserving"

---

docs/index.rst

Hi, some time back I added a feedstock on conda-forge so that docxtpl can also be installed from there. I maintain it. 
https://github.com/conda-forge/docxtpl-feedstock
In this PR, I simply added the instructions for how to install using conda.

Add conda install instructions

---

docxtpl/__init__.py

python-docx package can insert pictures in headers and footers now.
Fixes #51
changes :
- add current_rendering_part (header, document body or footer)
- invoke new_pic_inline from current_rendering_part, so the image relationship gets created correctly

Add insert InlineImage support to headers and footers

---

docxtpl/__init__.py

Reverts elapouya/python-docx-template#350
The tests does not pass (tests/runtests.py) : 
```
Traceback (most recent call last):
File "./cellbg.py", line 41, in <module>
tpl.render(context)
File "/home/elapouya/projects/python-docx-template/docxtpl/__init__.py", line 322, in render
tree = self.fix_shapes(xml_src)
File "/home/elapouya/projects/python-docx-template/docxtpl/__init__.py", line 344, in fix_shapes
mc = '{' + tree.nsmap['mc'] + '}'
KeyError: 'mc'
```

Revert "fix issue #345"

---

docxtpl/__init__.py

Before, the only searched picture tag was 'name', which corresponds to the file name of the image added to the docx. Also searching the title and description tags during image replacement makes creating docx templates to be rendered by this library more flexible and easier in editors which do not support viewing/editing the image original filename, such as Google Docs.

Search image title and description XML tags in image replacement

---

docxtpl/template.py

Those type hints are minimum which makes library easier to use. I can add more type hints (internal type hints) after this is merged.

Add first type hints

---

docs/index.rst
docxtpl/__main__.py
docxtpl/template.py
tests/embedded.py

There are small typos in:
- docs/index.rst
- docxtpl/__main__.py
- docxtpl/template.py
- tests/embedded.py
Fixes:
- Should read `surrounding` rather than `surronding`.
- Should read `rendering` rather than `rendring`.
- Should read `providing` rather than `provinding`.
- Should read `optionally` rather than `optionnally`.
- Should read `optional` rather than `optionnal`.
- Should read `necessary` rather than `neccessary`.
- Should read `existing` rather than `exsting`.
- Should read `embedded` rather than `embdded`.
- Should read `dictionaries` rather than `dictionnaries`.
- Should read `cleaning` rather than `cleanning`.
- Should read `catches` rather than `cacthes`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

docs/index.rst

I was using your library for my project, and I noticed some typos in the documentation, specifically in the "Sub-documents" section. This is a very useful tool so I want to make sure everyone can understand how to use it. The "Sub-documents" section is the only place where I made edits, but if you would like someone to look over the rest then I would be happy to help! If I misinterpreted what you originally meant, please let me know.

Improved the readability of the Sub-documents section of documentation.

---

docxtpl/richtext.py

When `RichText` elements are used with the `highlight` attributes, the generated document contains errors.
Fixing the xml properties seemed to produce correct documents.
Proof-of-Concept code:
```python3
from docxtpl import RichText, DocxTemplate
tpl = DocxTemplate('poc.docx')
YELLOW = 'ffe699'
normal_string = 'Lorem ipsum dolor sit amet, consectetur adipisici elit'
rich_string = 'String with a yellow highlight'
rt_embedded = RichText(f'{rich_string}', highlight=YELLOW)
context = {
'example' : rt_embedded,
}
tpl.render(context)
tpl.save('richtext.docx')
```
current:
fixed:

fixed element properties for highlighted text

---

docxtpl/template.py

They capture wrong xml tags, for example: `r'<w:t(?:[^>]*)?>.*?</w:t>'` captures not only <w:t>, but also <w:tc>, <w:tcBorders> etc.

Fix: add whitespace to regexp

---

docxtpl/template.py

I got an error from `docxcompose.composer.add_footnotes()` after upgrading `docxtpl` to 0.19.0.
> ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
I was able to avoid this error by making the change in this pull request, which ensures that the modified XML is written back to the `docx` document as `bytes`.
I'm not an authority on whether `part._blob` should be `bytes` or not, but it seems that way based on how this change fixes the problem I was having with `docxcompose`.

encode XML as bytes in render_footnotes()

---

docxtpl/template.py

I have no idea why it's necessary to raise an exception if a picture was not found in the template. My approach is to add a flag that allows us just to skip missing images.

Possibility to skip missing pictures

---

docxtpl/richtext.py

This PR fixes RTL text formatting in the RichText class with focus on bold/italic rendering:
**Complex Script Support:**
1. Added <w:bCs/> for **bold** Arabic text
2. Added <w:iCs/> for _italic_ RTL text
**RTL Text Handling**
1. Proper right-to-left paragraph direction
2. Language-specific text shaping (ar-SA, etc.)
**Testing Performed**
Verified rendering of:
- Mixed English/Arabic paragraphs
- Bold+italic combinations

Add RTL support for bold/italic text

---

.github/workflows/codestyle.yml
CHANGES.rst
docs/index.rst
docxtpl/__init__.py
docxtpl/template.py
setup.py

Move `docxcompose` to optional group 'subdoc', which can be installed by: `pip install "docxtpl[subdoc]"`
Related issue: #605 #602

Move docxcompose to optional dependency
